<?php

/**
 * Title: PRO: Latest Posts List with Ajax Load More 2
 * Slug: cozy-essential-addons/modestra-post-list-alternate
 * Categories: posts
 */
?>
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}},"layout":{"type":"constrained","contentSize":"980px"}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--70);padding-right:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--70);padding-left:var(--wp--preset--spacing--40)"><!-- wp:heading {"textAlign":"center","level":3,"style":{"spacing":{"margin":{"bottom":"40px"}}},"fontSize":"large"} -->
    <h3 class="wp-block-heading has-text-align-center has-large-font-size" style="margin-bottom:40px"><?php esc_html_e('Post List Alternate Featured Image and Load more ajax on Scroll', 'cozy-essential-addons') ?></h3>
    <!-- /wp:heading -->

    <!-- wp:cozy-block/magazine-list {"clientId":"8971a7a8-d6ff-484d-b6bb-784d3f36c9e1","perPage":5,"enableOptions":{"heading":false,"subHeading":false,"ignoreSticky":true,"postImage":true,"postContent":true,"postExcerpt":29,"readMore":true,"postAuthor":true,"postComments":true,"postDate":true,"postCategories":true},"headingLabel":"Latest Posts","headerBox":{"tabAlign":"space-between","padding":{"top":"6px","right":"6px","bottom":"6px","left":"6px"},"margin":{"top":"0px","bottom":"12px"},"border":{"top":{"width":"","style":"","color":""},"right":{"width":"","style":"","color":""},"bottom":{"width":"0px","style":"none"},"left":{"width":"","style":"","color":""}},"radius":"0px","color":{"bg":""}},"postBoxStyles":{"padding":{"top":"20px","right":"20px","bottom":"20px","left":"20px"},"margin":{"top":"0px","bottom":"0px"},"border":{"color":"#dedede","style":"solid","width":"1px"},"radius":"20px","color":{"bg":"","bgHover":"","borderHover":""},"shadow":{"enabled":false,"horizontal":0,"vertical":0,"blur":0,"spread":0,"color":"","position":""},"shadowHover":{"enabled":false,"horizontal":0,"vertical":0,"blur":0,"spread":0,"color":"","position":""},"hoverEffect":true},"postOptions":{"column":1,"gap":"28px","rowReverse":true,"textAlign":"left","image":{"position":"left","width":"30%","height":"210px","radius":"20px","hoverEffect":true},"content":{"gap":"28px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"title":{"margin":{"top":"8px","bottom":"6px"},"font":{"size":"24px","weight":"600","family":""},"letterCase":"none","color":{"text":"#090b10","textHover":"#FF598E"}}},"postMeta":{"margin":{"top":"8px","bottom":"8px"},"font":{"size":"14px","weight":"400","family":""},"letterCase":"none","color":{"text":"#a6a4a4","textHover":"#FF598E"}},"readMore":{"padding":{"top":"5px","right":"10px","bottom":"5px","left":"10px"},"margin":{"top":"16px","bottom":"0px"},"border":{"color":"#4f43ff","style":"solid","width":"1px"},"radius":"0px","font":{"size":"14px","weight":"500","family":""},"letterCase":"none","textAlign":"left","color":{"text":"#4F43FF","textHover":"#FF598E","bg":"","bgHover":"","borderHover":"#FF598E"}},"ajaxLoader":{"enabled":true,"type":"scroll","label":"Load More","loadingText":"","minWidth":"95px","content":10,"padding":{"top":"12px","right":"24px","bottom":"12px","left":"24px"},"margin":{"top":"48px","bottom":"0px"},"border":{"width":"","style":"","color":""},"radius":"100px","font":{"size":"14px","weight":"500","family":""},"letterCase":"none","textAlign":"center","color":{"text":"#fff","textHover":"","spinnerPrimary":"#FF598E","spinnerSecondary":"#FFFFFF","bg":"#4F43FF","bgHover":"#FF598E","borderHover":""}}} /-->
</div>
<!-- /wp:group -->